// Generated by CoffeeScript 2.7.0
  // zh-utils.coffee
import {
  undef,
  defined,
  notdefined,
  OL,
  getOptions,
  isString,
  isArray,
  isInteger
} from '@jdeighan/base-utils';

import {
  dbg,
  dbgEnter,
  dbgReturn
} from '@jdeighan/base-utils/debug';

import {
  assert
} from '@jdeighan/base-utils/exceptions';

import {
  eachCharInString
} from '@jdeighan/base-utils';

// ---------------------------------------------------------------------------
export var isZhChars = function(str) {
  var ch, i, len, ref;
  ref = [...str];
  for (i = 0, len = ref.length; i < len; i++) {
    ch = ref[i];
    if (!ch.match(/[\u4E00-\u9FFF]/)) {
      return false;
    }
  }
  return true;
};


// ---------------------------------------------------------------------------
export var isPinyinChars = function(str) {
  var ch, i, len, ref;
  ref = [...str];
  for (i = 0, len = ref.length; i < len; i++) {
    ch = ref[i];
    if (!ch.match(/[a-z 'āáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ]/)) {
      return false;
    }
  }
  return true;
};
